### Variables globales
@host = {{host}}
@contentType = {{contentType}}

# Nota: Si este endpoint requiere autenticación, primero ejecuta el login en auth.http
# El token JWT se guardará automáticamente y estará disponible para todas las peticiones


### Buscar en todas las categorías con el término "crema"
# Este endpoint devuelve una lista paginada de productos de todas las categorías que contienen "crema" en su nombre
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": " ",
  "categories": ["materia prima", "material empaque", "semiterminado", "terminado"],
  "page": 0,
  "size": 10
}

### Prueba de materiales
# solo materias primas
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": "",
  "categories": ["materia prima"],
  "page": 0,
  "size": 10
}

###
# ambos materias primas y materiales de empaque
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": "",
  "categories": ["materia prima", "material empaque"],
  "page": 0,
  "size": 10
}

###
# solo materiales de empaque
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": "",
  "categories": ["material empaque"],
  "page": 0,
  "size": 10
}

### Terminados
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": "",
  "categories": ["terminado"],
  "page": 0,
  "size": 10
}

### Semiterinados
POST {{host}}/productos/consulta1
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "search": "",
  "categories": ["semiterminado"],
  "page": 0,
  "size": 10
}

