
spring:
  application:
    name: lac-manufacture

  config:
    additional-location: classpath:application-secrets.properties

  datasource:
    #url: jdbc:mysql://localhost:3306/lacm-planta?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql-container:3306/lacm-planta?createDatabaseIfNotExist=true
    username: root
    password: la1234
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 30000
server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

#security:
#  user:
#   name: admin
#   password: admin