
spring:
  application:
    name: lac-manufacture

  config:
    additional-location: classpath:application-secrets.properties

  datasource:
    #url: jdbc:mysql://mysql-container:3306/lacm-planta?createDatabaseIfNotExist=true # OLD MULTI-CONTAINER URL
    #url: jdbc:postgresql://dpg-cpuutq1u0jms73ahqplg-a.oregon-postgres.render.com:5432/lacmdb # RENDER EXTERNAL
    #url: jdbc:postgresql://dpg-cpuutq1u0jms73ahqplg-a:5432/lacmdb # RENDER INTERNAL
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true # LOCAL DEV
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        #dialect: org.hibernate.dialect.MySQL8Dialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 30000
server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false

#security:
#  user:
#   name: admin
#   password: admin