### Variables globales
@host = {{host}}
@contentType = {{contentType}}

### Obtener todos los endpoints
# Este endpoint devuelve una lista de todos los endpoints disponibles en la aplicación
GET {{host}}/api/backend-info/endpoints
Accept: {{contentType}}

### Obtener detalles de un endpoint específico
# Este endpoint devuelve información detallada sobre un endpoint específico
# Requiere los parámetros path y method
GET {{host}}/api/backend-info/endpoints/details?path=/api/emails/simple&method=POST
Accept: {{contentType}}

### Ejemplo alternativo para obtener detalles de otro endpoint
# Puedes modificar los parámetros path y method para obtener detalles de diferentes endpoints
GET {{host}}/api/backend-info/endpoints/details?path=/api/backend-info/endpoints&method=GET
Accept: {{contentType}}
