### Variables globales
@host = {{host}}
@contentType = {{contentType}}
@auth_token = {{auth_token}}

### Obtener notificaciones para un usuario específico
# Este endpoint devuelve las notificaciones para todos los módulos a los que tiene acceso el usuario
GET {{host}}/notificaciones/notifications4user?username=master
Accept: {{contentType}}
Authorization: Bearer {{auth_token}}

### Obtener notificaciones para otro usuario
# Prueba con un usuario diferente
GET {{host}}/notificaciones/notifications4user?username=usuario1
Accept: {{contentType}}
Authorization: Bearer {{auth_token}}

### Obtener notificaciones para un usuario sin accesos
# Prueba con un usuario que no tiene acceso a ningún módulo
GET {{host}}/notificaciones/notifications4user?username=usuariosinacceso
Accept: {{contentType}}
Authorization: Bearer {{auth_token}}

### Obtener notificaciones sin autenticación
# Esta petición debería fallar si la API requiere autenticación
GET {{host}}/notificaciones/notifications4user?username=master
Accept: {{contentType}}